In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [5]:
df = pd.DataFrame(response.json())
df

,page,results,total_pages,total_results
0,1,"{'adult': False, 'backdrop_path': '/zfbjgQE1uS...",506,10103
1,1,"{'adult': False, 'backdrop_path': '/tmU7GeKVyb...",506,10103
2,1,"{'adult': False, 'backdrop_path': '/kGzFbGhp99...",506,10103
3,1,"{'adult': False, 'backdrop_path': '/zb6fM1CX41...",506,10103
4,1,"{'adult': False, 'backdrop_path': '/bxgTSUenZD...",506,10103
5,1,"{'adult': False, 'backdrop_path': '/6oaL4DP75y...",506,10103
6,1,"{'adult': False, 'backdrop_path': '/oOv2oUXcAa...",506,10103
7,1,"{'adult': False, 'backdrop_path': '/90ez6ArvpO...",506,10103
8,1,"{'adult': False, 'backdrop_path': '/vxJ08Svwom...",506,10103
9,1,"{'adult': False, 'backdrop_path': '/hiKmpZMGZs...",506,10103
10,1,"{'adult': False, 'backdrop_path': '/suaEOtk1N1...",506,10103
11,1,"{'adult': False, 'backdrop_path': '/8x9iKH8kWA...",506,10103
12,1,"{'adult': False, 'backdrop_path': '/2u7zbn8Eud...",506,10103
13,1,"{'adult': False, 'backdrop_path': '/ghgfzbEV7k...",506,10103
14,1,"{'adult': False, 'backdrop_path': '/x4biAVdPVC...",506,10103
15,1,"{'adult': False, 'backdrop_path': '/sJNNMCc6B7...",506,10103
16,1,"{'adult': False, 'backdrop_path': '/7TF4p86Zaf...",506,10103
17,1,"{'adult': False, 'backdrop_path': '/8sNiAPPYU1...",506,10103
18,1,"{'adult': False, 'backdrop_path': '/tDFvXn4tan...",506,10103
19,1,"{'adult': False, 'backdrop_path': '/gavyCu1UaT...",506,10103

In [4]:
df = pd.DataFrame(response.json()['results'])
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,42.1084,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.708,28172
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",41.1643,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,21361
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,18.4965,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.570,12909
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,39.7665,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.564,16379
4,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,18.2538,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.548,9089
5,False,/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",27.8071,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.537,17063
6,False,/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,35.0763,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.519,33748
7,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",10.0729,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.516,4483
8,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,40.4339,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.504,18020
9,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",32.0756,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.500,18967
10,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",54.2890,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.489,28588
11,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,27.5640,/8GJsy7w7frGquw1cy9jasOGNNI1.jpg,2016-08-26,Your Name.,False,8.485,11726
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,26.8506,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.483,24998
13,False,/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,25.9294,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.467,28119
14,False,/x4biAVdPVCghBlsVIzB6NmbghIz.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,48.0579,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.463,8945
15,False,/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,11.7367,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.457,3873
16,False,/7TF4p86ZafnxFuNqWdhpHXFO244.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",49.1941,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.455,13307
17,False,/8sNiAPPYU14PUepFNeSNGUTiHW.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,47.2772,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.454,36986
18,False,/tDFvXn4tane9lUvFAFAUkMylwSr.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0140,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.451,5851
19,False,/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,17.9501,/74hLDKjD5aGYOotO6esUVaeISa2.jpg,1997-12-20,Life Is Beautiful,False,8.449,13318

In [6]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,42.1084,8.708,28172
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.1643,8.687,21361
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,18.4965,8.570,12909
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,39.7665,8.564,16379
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2538,8.548,9089

In [9]:
df = pd.DataFrame()

In [10]:
df

Empty DataFrame
Columns: []
Index: []

In [28]:
lst = []
for i in range(1,501): # Click on the url to get the range and check no of pages
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    lst.append(temp_df)
    print (i)
    
df = pd.concat(lst)
df
# only runs till index 500. Maybe API limit

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,42.1084,8.708,28172
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.1643,8.687,21361
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,18.4965,8.570,12909
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,39.7665,8.564,16379
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2538,8.548,9089
...,...,...,...,...,...,...,...
15,455551,The Recall,When five friends vacation at a remote lake ho...,2017-06-02,2.4590,4.585,346
16,11411,Superman IV: The Quest for Peace,With global superpowers engaged in an increasi...,1987-07-24,3.6615,4.583,1281
17,10285,Jason Goes to Hell: The Final Friday,Jason Voorhees is tracked down and blown to bi...,1993-08-13,3.0246,4.600,1027
18,248504,Sharknado 2: The Second One,A freak weather system turns its deadly fury o...,2014-07-31,1.1237,4.559,660
19,447273,Snow White,"Following the benevolent King's disappearance,...",2025-03-19,84.4751,4.556,574

In [19]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,42.1084,8.708,28172
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.1643,8.687,21361
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,18.4965,8.570,12909
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,39.7665,8.564,16379
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2538,8.548,9089
...,...,...,...,...,...,...,...
15,419430,Get Out,Chris and his girlfriend Rose go upstate to vi...,2017-02-24,16.1787,7.618,17819
16,4235,The Sicilian Clan,An ambitious mobster plans an elaborate diamon...,1969-12-05,4.1603,7.615,334
17,637649,Wrath of Man,A cold and mysterious new security guard for a...,2021-04-22,26.1996,7.600,5545
18,10331,Night of the Living Dead,A group of strangers trapped in a farmhouse fi...,1968-10-04,6.3299,7.616,2521
19,746,The Last Emperor,"A dramatic history of Pu Yi, the last of the E...",1987-10-04,5.6630,7.616,1734

In [22]:
df.shape

(8551, 7)

In [23]:
df.to_csv('movies.csv')